# Please do not edit this file, as it is managed by roar
{ rUtils, ... }:
final: prev:
let
  buildCranRPackage = rUtils.lib.buildCranRPackage final prev;
  buildBiocRPackage = rUtils.lib.buildBiocRPackage final prev;
  buildGitHubRPackage = rUtils.lib.buildGitHubRPackage final prev;
  buildCraneRPackage = rUtils.lib.buildCraneRPackage final prev;
in
{
  rPackages = prev.rPackages.override {
    overrides = {
    };
  };
}
